/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChargingStationDeviceAllOf { 
    deviceIdCharger?: number;
    uuid?: string;
    ocppAvailable?: boolean;
    chargePointStatus?: ChargingStationDeviceAllOf.ChargePointStatusEnum;
}
export namespace ChargingStationDeviceAllOf {
    export type ChargePointStatusEnum = 'Available' | 'Preparing' | 'Charging' | 'SuspendedEVSE' | 'SuspendedEV' | 'Finishing' | 'Reserved' | 'Unavailable' | 'Faulted';
    export const ChargePointStatusEnum = {
        Available: 'Available' as ChargePointStatusEnum,
        Preparing: 'Preparing' as ChargePointStatusEnum,
        Charging: 'Charging' as ChargePointStatusEnum,
        SuspendedEvse: 'SuspendedEVSE' as ChargePointStatusEnum,
        SuspendedEv: 'SuspendedEV' as ChargePointStatusEnum,
        Finishing: 'Finishing' as ChargePointStatusEnum,
        Reserved: 'Reserved' as ChargePointStatusEnum,
        Unavailable: 'Unavailable' as ChargePointStatusEnum,
        Faulted: 'Faulted' as ChargePointStatusEnum
    };
}


