/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceGroupCreate } from './deviceGroupCreate';
import { FetchDevice200Response } from './fetchDevice200Response';
import { EnergyDeviceGroupCreate } from './energyDeviceGroupCreate';


/**
 * @type CreateGroupRequest
 * @export
 */
export type CreateGroupRequest = DeviceGroupCreate | EnergyDeviceGroupCreate;

