/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterfaceConfig } from './interfaceConfig';


export interface DeviceCreateRequest { 
    interfaceConfig?: InterfaceConfig;
    unitId?: number;
    manufacturerId?: number;
    deviceType?: DeviceCreateRequest.DeviceTypeEnum;
    name?: string;
    deviceId?: number;
}
export namespace DeviceCreateRequest {
    export type DeviceTypeEnum = 'INVERTER';
    export const DeviceTypeEnum = {
        Inverter: 'INVERTER' as DeviceTypeEnum
    };
}


