/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterfaceConfig } from './interfaceConfig';


export interface Device {
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    interfaceConfig?: InterfaceConfig;
    name?: string;
    manufacturerId?: number;
    deviceId?: number;
    deviceType?: Device.DeviceTypeEnum;
    unitId: number;
    active: boolean;
    model?: string;
    groupId?: number;
}
export namespace Device {
    export type DeviceTypeEnum = 'INVERTER' | 'HYBRID_INVERTER' | 'BATTERY';
    export const DeviceTypeEnum = {
        Inverter: 'INVERTER' as DeviceTypeEnum,
        HybridInverter: 'HYBRID_INVERTER' as DeviceTypeEnum,
        Battery: 'BATTERY' as DeviceTypeEnum
    };
}


