/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FetchDevices200ResponseInner } from './fetchDevices200ResponseInner';


export interface DeviceGroupCreate { 
    name?: string;
    devices?: Array<FetchDevices200ResponseInner>;
    /**
     * Die Gruppen Typen
     */
    type?: DeviceGroupCreate.TypeEnum;
}
export namespace DeviceGroupCreate {
    export type TypeEnum = 'PLANT' | 'CHARGING_STATION' | 'HEAT_PUMP' | 'BATTERY' | 'HOME';
    export const TypeEnum = {
        Plant: 'PLANT' as TypeEnum,
        ChargingStation: 'CHARGING_STATION' as TypeEnum,
        HeatPump: 'HEAT_PUMP' as TypeEnum,
        Battery: 'BATTERY' as TypeEnum,
        Home: 'HOME' as TypeEnum
    };
}


