/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnergyDistributionResponse { 
    event?: EnergyDistributionResponse.EventEnum;
    description?: string;
    name?: string;
}
export namespace EnergyDistributionResponse {
    export type EventEnum = 'RENEWABLE_ENERGY' | 'UNMANAGED' | 'MANAGED';
    export const EventEnum = {
        RenewableEnergy: 'RENEWABLE_ENERGY' as EventEnum,
        Unmanaged: 'UNMANAGED' as EventEnum,
        Managed: 'MANAGED' as EventEnum
    };
}


