/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnergyDistributionResponse } from './energyDistributionResponse';
import { InterfaceConfig } from './interfaceConfig';
import { HybridInverterDevice } from './hybridInverterDevice';
import { ChargingStationDevice } from './chargingStationDevice';


/**
 * @type FetchDevice200Response
 * @export
 */
export type FetchDevice200Response = ChargingStationDevice | HybridInverterDevice;

