/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceGroupRepresentation } from './deviceGroupRepresentation';
import { BiDirectionalEnergy } from './biDirectionalEnergy';
import { HomeDataRepresentation } from './homeDataRepresentation';
import { PlantDataRepresentation } from './plantDataRepresentation';


/**
 * @type FetchDeviceGroupData200Response
 * @export
 */
export type FetchDeviceGroupData200Response = DeviceGroupRepresentation | HomeDataRepresentation | PlantDataRepresentation;

