/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceGroupRepresentation } from './deviceGroupRepresentation';
import { BiDirectionalEnergy } from './biDirectionalEnergy';


export interface HomeDataRepresentation extends DeviceGroupRepresentation { 
    grid: BiDirectionalEnergy;
    peakKilowatt: number;
    activePower: number;
    batterySoc: number;
    batteryPower: BiDirectionalEnergy;
    houseHoldPower: number;
    heatPumpActive: boolean;
    chargingStation: BiDirectionalEnergy;
}
export namespace HomeDataRepresentation {
}


