/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceGroupRepresentation } from './deviceGroupRepresentation';


export interface HomeDataRepresentation extends DeviceGroupRepresentation { 
    peakKilowatt?: number;
    activePower?: number;
    batterySoc?: number;
    batteryPower?: number;
    houseHoldPower?: number;
    heatPumpActive?: boolean;
    chargingStationPower?: number;
}
export namespace HomeDataRepresentation {
}


