/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterfaceConnection } from './interfaceConnection';
import { InterfaceMapping } from './interfaceMapping';
import { MetaData } from './metaData';


export interface Interface { 
    version?: number;
    metaData?: MetaData;
    connection?: InterfaceConnection;
    mapping?: InterfaceMapping;
}

