/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterMapping { 
    register?: Array<number>;
    unit?: RegisterMapping.UnitEnum;
    type?: string;
    fc?: RegisterMapping.FcEnum;
    conversionMethod?: string;
}
export namespace RegisterMapping {
    export type UnitEnum = 'W' | 'KW' | 'KWH' | 'PERCENT';
    export const UnitEnum = {
        W: 'W' as UnitEnum,
        Kw: 'KW' as UnitEnum,
        Kwh: 'KWH' as UnitEnum,
        Percent: 'PERCENT' as UnitEnum
    };
    export type FcEnum = 'READ_COILS' | 'READ_DISCRETE_INPUTS' | 'READ_HOLDING_REGISTERS' | 'READ_INPUT_REGISTERS' | 'WRITE_SINGLE_COIL' | 'WRITE_SINGLE_REGISTER' | 'WRITE_MULTIPLE_COILS' | 'WRITE_MULTIPLE_REGISTERS';
    export const FcEnum = {
        ReadCoils: 'READ_COILS' as FcEnum,
        ReadDiscreteInputs: 'READ_DISCRETE_INPUTS' as FcEnum,
        ReadHoldingRegisters: 'READ_HOLDING_REGISTERS' as FcEnum,
        ReadInputRegisters: 'READ_INPUT_REGISTERS' as FcEnum,
        WriteSingleCoil: 'WRITE_SINGLE_COIL' as FcEnum,
        WriteSingleRegister: 'WRITE_SINGLE_REGISTER' as FcEnum,
        WriteMultipleCoils: 'WRITE_MULTIPLE_COILS' as FcEnum,
        WriteMultipleRegisters: 'WRITE_MULTIPLE_REGISTERS' as FcEnum
    };
}


