/**
 * Energy Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlantDeviceGroupUpdate } from './plantDeviceGroupUpdate';
import { FetchDevice200Response } from './fetchDevice200Response';
import { DeviceGroupUpdate } from './deviceGroupUpdate';


/**
 * @type UpdateGroupRequest
 * @export
 */
export type UpdateGroupRequest = DeviceGroupUpdate | PlantDeviceGroupUpdate;

